"""schema initial (suppliers, documents, invoices, invoice_lines, document_chunks)

Revision ID: c20e9c80396c
Revises: 
Create Date: 2026-09-22 15:58:39.763040

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c20e9c80396c'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Requis par document_chunks.embedding (VECTOR(1024)) ci-dessous. Sur la
    # DB de dev d'origine, l'extension avait été activée manuellement hors
    # migration — jamais rejouable sur une base neuve sans cette ligne.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('doc_type', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ocr_confidence', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint("doc_type IN ('invoice','contract','report')", name='ck_documents_doc_type')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('ice', sa.Text(), nullable=True),
    sa.Column('if_number', sa.Text(), nullable=True),
    sa.Column('rc', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.Text(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('total_ht', sa.Numeric(), nullable=True),
    sa.Column('tva_rate', sa.Numeric(), nullable=True),
    sa.Column('total_tva', sa.Numeric(), nullable=True),
    sa.Column('total_ttc', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.Text(), server_default='MAD', nullable=True),
    sa.Column('payment_status', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint("payment_status IN ('paid','unpaid')", name='ck_invoices_payment_status')
    )
    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('unit_price_ht', sa.Numeric(), nullable=True),
    sa.Column('total_ht', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_lines')
    op.drop_table('invoices')
    op.drop_table('document_chunks')
    op.drop_table('suppliers')
    op.drop_table('documents')
    # ### end Alembic commands ###
